# Generated by Django 5.0.4 on 2026-02-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
                ('dernier_rappel', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
