# Generated by Django 6.0.2 on 2026-02-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0002_pendingaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingaction',
            old_name='guild_id',
            new_name='channel_id',
        ),
    ]
