# Generated by Django 6.0.2 on 2026-02-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0003_rename_guild_id_pendingaction_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
